services:
  rabbitmq:
    image: "rabbitmq"
    ports:
      - "5672:5672"
  azurite:
    image: "mcr.microsoft.com/azure-storage/azurite"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
  analyze-worker:
    build:
      context: .
      dockerfile: build/docker/worker_dockerfile
    image: worker
    depends_on:
      - rabbitmq
    environment:
      - WORKER_APP=contract_red_flags.tasks.analyze
      - CELERY_BROKER=amqp://rabbitmq
      - CELERY_RESULT_BACKEND=rpc://
  api:
    build:
      context: .
      dockerfile: build/docker/api_dockerfile
    image: api
    depends_on:
      - rabbitmq
    ports:
     - "8000:8000"
    environment:
      - CELERY_BROKER=amqp://rabbitmq
      - CELERY_RESULT_BACKEND=rpc:// 